service: first-test

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-2
  environment:
    ENV: aws
  
package:
  individually: true

plugins:
  - serverless-webpack

custom:
  webpackIncludeModules: true
  webpack: ./aws.webpack.config.js

functions:
  process-xml:
    handler: process-xml.handler
  getDebitItems:
    handler: get-debit-items.handler
    events:
      - http:
          method: GET
          path: get-debit-items
          cors: true
